{% set name = "ppft" %}
{% set version = "1.6.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 1beab076fb9452fd729a9f1183e990d016fcd8ee67252f6897f3785d5b807a22

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - six >=1.7.3
  run:
    - python
    - six >=1.7.3

test:
  imports:
    - ppft

about:
  home: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki.html
  license: BSD-3-Clause
  license_file: COPYING
  summary: distributed and parallel python

extra:
  recipe-maintainers:
    - jschueller
    - synapticarbors
