{% set name = "ppft" %}
{% set version = "1.6.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: cd1e39129fc9cbd4a877b1ff4fc5018051183c11bc9c9c0922efad80c57174f6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - six >=1.7.3
  run:
    - python
    - six >=1.7.3

test:
  imports:
    - ppft

about:
  home: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki.html
  license: BSD-3-Clause
  license_file: COPYING
  summary: distributed and parallel python

extra:
  recipe-maintainers:
    - jschueller
    - synapticarbors
