{% set name = "ppft" %}
{% set version = "1.7.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f933f0404f3e808bc860745acb3b79cd4fe31ea19a20889a645f900415be60f1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python =2.7|>=3.6
    - pip
    - six >=1.7.3
  run:
    - python =2.7|>=3.6
    - six >=1.7.3

test:
  imports:
    - ppft

about:
  home: https://github.com/uqfoundation/ppft
  license: BSD-3-Clause
  license_file: COPYING
  summary: distributed and parallel python

extra:
  recipe-maintainers:
    - jschueller
    - synapticarbors
