appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: eV2hn975CCdB/TutnB+UKhBz3KevTSesq1QakTWiDo3gjRFjD08fTm2VbFSt8QcEsmYR+JcaSiiZvAvLwCiNubOqbysyiDhXyDLM4A3+iVKtHV+xTpyjhBRH3JWptH2ZwzYQH5OqCBidxQdQYD+VdGxFJukwMHi+O9AdMiwZM9nPU++cZBSc5WKofrvexZP/AOiNhs/T6V4sKL5nb524oA4g2YH9DXPxl5AUTlbVQH3Guj7T6WKRTl2uzlvN7LlC8CnMCRclTzvp3B4WMY3a8sKn9phi8Qs38uDi7uVpIU9zt8bRRGoNw53v+NkwgSWKcdckcJPbOtFYUaLz+iT7NvbLa+bxbn9VnnpnCEBl6haJWXq8tjlNgEXjB5cdTla5r1NdHwZu/brtKzitIbxlGxQW0FW8f9TKHIRZ33tRkSgQWB7Ni8MnE/9lx9TRq6j2Lsfb+SxHp4V/Ie54KJve41G1BFTjlvcpttGPoBp9w9a7YGscHaIYdd9tM6f63N3X9J+gVm08aBWG7nlkFAlOd0PWhRDjfDVJQBg4FDgV8ebrljSBBODrc29RMJIpXkVCl3R2oJSIrfZniWOSbDloMJsUAclRxNM5BnL593Cm0+3ihfNh7oosdtIGgkcYe6k/E12EHJidratDmMmG/QKdFkA0l7yw/A6lDSiqGtp23xE=}
provider:
  win: azure
