travis:
  secure:
    BINSTAR_TOKEN: Es8+zjOj6xVFE8SzBY5zSKtiS7HHMcj/6Gk5QnaDH6VEqxcrhK1WA/Cz8ibfKosSDXJTb340ahEmowwLSogZVd/Pa0COUBbw3ysfNPW9JFkkGlMkQHujkzjnkN4+UbIYRPtWRNxQgO6HaemZsp71WusFeaTiGV88GpOaqasZGo77UD7m7gvNxtN8r7+A4g6RIwsaxIRKHcAXh56fizJ0tZgwgCKU7KDWG7oOjUGexl+of284gZHHj6anrBmCQEgoA4fJEedtdLahD7DuHJwfiQ1VX+i1bFNhC0CTJt4y696mjN8PqQePTOyS4kNDy2gdA4xcBAyZYIFYcSp/sYlkKuJcSeVm3WHpT2PW71YCYcmL78RM9YuSr5/iBGp/zxnQIHStu25rp+KfilS4PNZ84ULxN02Cs00TErvxOCkIzJDtGtsWj9HMu7Hz9zwlgevWXIoxD3In6XPzZUnigLrjIQbEXivgK+KmX6QCRisws/5cPNPWcWv7NhQcOwVY5wDtGBavG1xFq2sC8mjo72j/insOiAWFbxjhzZtu7dnk8wLSWxG4v1jaLLDSuUdiOLFC0orkFSxezWCPBqwJCkX0husl/rfhdeMeMOKxZ2Y/J9b6RGU7RU5sf6SjWgTSJVIDV+k7HC6q0fQ7SwI8cYhjyvG8y36oVT1CSoz99wyj2nY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
