travis:
  secure:
    BINSTAR_TOKEN: SC0F8I8N/h1dRYrPDCAGpN5zvq7uFRBexLGJa1JsJXcrT4+fxf5Lwehn0IMk3ioKetscV5v183ztdGS6mGrjIkNNwXz9HXCqa/UBP9rRATimZPXcuZgJYyC99/ZcJ/VQk11ucgr+xQIwCklASTCAzIIthPT9SCPCLvhI9dtipgJbVmitjgfRbsdaiOO+OFmdG/z6u95ocZYuqKsQ+Mc3zKSPU0hD5xmvPEkvpjdyfgHdJj03+rwaWhIlxwKyK9QCUtIyTSowXlPLnGVevF/TO8Z61dSp+Qm78cwgufj0LLRdBBvHG61i8vYy7nDLnmV2xCtsu20D9HopoVJt37rfjZ4oE43fiwT47fhAZchRaK2xLy/qxPd3TUic/mgs6YItNT7NfQyZxBVmjPDdaTo3Vrmtiww0UZpGN5Nvd9mV281tZ6FaGf0ri0G402A4EyEG3L/4UF3YZwS0zzBuPXy5unU8xF6bc5Ucih3FwMoNk2t6L8fvwLc56mQAatcLfHCyPvEffvEv96emuQsaNyvVq29XTvl49G6WZD4NL4o4vOGGIRir3CM9U4epz1yW5pSBC5OZ/IuftSKBaqK+h85PSI54qbcRiZiQn8GNKeB5cL/5Z65E5Pzdv28FcJtej7yDcyWfXuTBvkib8sz0rkFK5CBHxtI6g9S7DFXW3wkRrvo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
